---
title: "02 Transformacion y modelaje"
author: "Leonardo Daniel Rosas Rios"
date: "2025-08-26"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
#Bibliotecas
library(readxl)
library(dplyr)
library(ISOweek)
library(reshape2)
library(ggplot2)
library(writexl)
library(sandwich)   
library(lmtest)     
library(GGally)
library(tseries)



#Funciones
source("R/utils.R")

#semilla
set.seed(123)


```


# Lectura de datos
```{r}
#Lectura de base de datos
Evalim <- read_excel("Data/Base_limpia.xlsx")

```



# Modelos


## Regresion lineal simple 

```{r}
# Modelo 1: Y = Cartera Vigente, X = Semanas de Antigüedad
modelo1 <- lm(`Cartera Vigente` ~ `Semanas de Antigüedad`, data = Evalim)

# Resumen del modelo
summary(modelo1)
```




$$
\text{Cartera Vigente} = 9{,}285{,}302 \;+\; 31{,}297 \times \text{Semanas de Antigüedad}
$$


```{r}
par(mfrow = c(2,2))  

plot(modelo1, which = 1, col = "blue", pch = 19)   # Residuales vs Ajustados
plot(modelo1, which = 2, col = "red", pch = 19)    # QQ-plot
plot(modelo1, which = 3, col = "darkgreen", pch = 19) # Escala-Localidad
plot(modelo1, which = 5, col = "purple", pch = 19) # Valores influyentes

par(mfrow = c(1,1))

```


```{r}
# residuos del modelo
residuos1 <- residuals(modelo1)

# Test de Jarque-Bera
jarque.bera.test(residuos1)

```









## Regresion lienal multiple



```{r}
# Todas las variables
modelo2 <- lm(`Cartera Vigente` ~ `Semanas de Antigüedad` + `Colocación Total` + `Colocación objetivo Asesor`, 
              data = Evalim)


summary(modelo2)

```
```{r}
# residuos del modelo
residuos2 <- residuals(modelo2)

# Test de Jarque-Bera
jarque.bera.test(residuos2)

```
```{r}
par(mfrow = c(2,2))  

plot(modelo2, which = 1, col = "deepskyblue2", pch = 19)     # Residuales vs Ajustados
plot(modelo2, which = 2, col = "darkorange1", pch = 19)      # QQ-plot
plot(modelo2, which = 3, col = "mediumseagreen", pch = 19)   # Escala-Localidad
plot(modelo2, which = 5, col = "magenta2", pch = 19)         # Valores influyentes

par(mfrow = c(1,1))


```






## Regresion lineal multiple con transformacion log

```{r}

# 1) Modelo con logs (respuesta y predictores)
modelo_log <- lm(
  log1p(`Cartera Vigente`) ~ log1p(`Semanas de Antigüedad`) +
                              log1p(`Colocación Total`) +
                              log1p(`Colocación objetivo Asesor`),
  data = Evalim
)

summary(modelo_log)
```


```{r}
par(mfrow = c(2,2))

plot(modelo_log, which = 1, col = "dodgerblue3", pch = 19)   # Residuales vs Ajustados
plot(modelo_log, which = 2, col = "gold2", pch = 19)         # QQ-plot
plot(modelo_log, which = 3, col = "springgreen3", pch = 19)  # Escala-Localidad
plot(modelo_log, which = 5, col = "tomato2", pch = 19)       # Valores influyentes

par(mfrow = c(1,1))


```



```{r}
# residuos del modelo
residuos <- residuals(modelo_log)

# Test de Jarque-Bera
jarque.bera.test(residuos)
```

## Regresion lineal multiple con trasformacion Yeo–Johnson



```{r}
library(caret)

# 1) Selecciona SOLO las columnas numéricas que vas a transformar
vars_num <- c("Semanas de Antigüedad",
              "Colocación Total",
              "Colocación objetivo Asesor",
              "Cartera Vigente")

# 2) Arma un data.frame con esas columnas (y cualquier otra que necesites como ID/semana)
df_model <- Evalim[, c("Semana ID", vars_num)]

# 3) Preprocesamiento Yeo–Johnson (soporta negativos y ceros)
pre_yj <- preProcess(df_model[, vars_num], method = "YeoJohnson")

# 4) Aplica la transformación a esas columnas
df_yj <- df_model
df_yj[, vars_num] <- predict(pre_yj, df_model[, vars_num])

# 5) Ajusta el modelo lineal en niveles (sobre datos transformados)
modelo_yj <- lm(`Cartera Vigente` ~
                  `Semanas de Antigüedad` +
                  `Colocación Total` +
                  `Colocación objetivo Asesor`,
                data = df_yj)

summary(modelo_yj)

```

```{r}
par(mfrow = c(2,2))

plot(modelo_yj, which = 1, col = "dodgerblue3", pch = 19)   # Residuales vs Ajustados
plot(modelo_yj, which = 2, col = "gold2", pch = 19)         # QQ-plot
plot(modelo_yj, which = 3, col = "springgreen3", pch = 19)  # Escala-Localidad
plot(modelo_yj, which = 5, col = "tomato2", pch = 19)       # Valores influyentes

par(mfrow = c(1,1))

```





```{r}
# Instalar si no lo tienes
# install.packages("tseries")
library(tseries)

# Sacar residuos del modelo
res_yj <- residuals(modelo_yj)

# Test de Jarque-Bera
jarque.bera.test(res_yj)

```


# Cumplimiento de indicadores



```{r}
#Indicador de colocacion 
Evalim$'Cumplimiento colocacion' <- Evalim$`Colocación Total` / Evalim$`Colocación objetivo Asesor`
Evalim
```


```{r}
# Predicción de cartera objetivo

Evalim$'Objetivo Cartera' <- predict(modelo1, newdata = Evalim)
Evalim
```

```{r}

Evalim$'Objetivo Cartera' <- predict(modelo1, newdata = Evalim)
Evalim
```



```{r}
# Cumplimiento
Evalim$'Cumplimiento Cartera' <- Evalim$`Cartera Vigente` / Evalim$'Objetivo Cartera'
Evalim
```


```{r}

colSums(is.na(Evalim))



```


```{r}
colnames(Evalim)
```




```{r}
#write_xlsx(Evalim, "Data/Base_yjinidicadores.xlsx")

```








