---
title: "Clasificacion trabajadores"
author: "Leonardo Daniel Rosas Rios"
date: "2025-08-26"
output: html_document
---


```{r, echo=TRUE, message=FALSE, warning=FALSE}
#Bibliotecas
library(readxl)
library(dplyr)
library(ISOweek)
library(reshape2)
library(ggplot2)
library(writexl)
library(sandwich)   
library(lmtest)     
library(GGally)
library(tseries)



#semilla
set.seed(123)


```




# Lectura de datos
```{r}
#Lectura de base de datos
Evalim <- read_excel("Data/Base_inidicadores.xlsx")
Evalim
```








# Clasificacion de asesores en niveles de productividad


## Clasificacion cuadrantes
```{r}

Evalim <- Evalim %>%
  mutate(
    Nivel_Prod = case_when(
      `Cumplimiento colocacion` > 1 & `Cumplimiento Cartera` > 1 ~ 1,
      `Cumplimiento colocacion` <= 1 & `Cumplimiento Cartera` > 1 ~ 2,
      `Cumplimiento colocacion` > 1 & `Cumplimiento Cartera` <= 1 ~ 3,
      TRUE ~ 4
    )
  )



ggplot(Evalim, aes(x = `Cumplimiento colocacion`,
                   y = `Cumplimiento Cartera`,
                   color = factor(Nivel_Prod))) +
  geom_point(alpha = 0.4, size = 1) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(color = "Nivel",
       x = "Cumplimiento Colocación",
       y = "Cumplimiento Cartera") +
  theme_minimal() +
  scale_color_manual(values = c(
    "1" = "#F8766D",  # rojo
    "2" = "#7CAE00",  # verde
    "3" = "#00BFC4",  # turquesa
    "4" = "#C77CFF"   # morado
  ))

```


```{r}
table(Evalim$Nivel_Prod)
prop.table(table(Evalim$Nivel_Prod))

```


```{r}
colSums(is.na(Evalim))

```






## Clasificacion k-means

```{r,warning=FALSE, message=FALSE}

# Matriz de features
features <- Evalim %>%
  select(`Cumplimiento colocacion`, `Cumplimiento Cartera`) %>%
  na.omit()

# Escalamos
features_scaled <- scale(features)

# k-means (4 clusters)
km <- kmeans(features_scaled, centers = 4, nstart = 25)

# Añadimos clusters al df
Evalim$Cluster <- NA
Evalim$Cluster[as.numeric(rownames(features))] <- km$cluster


ggplot(Evalim, aes(x = `Cumplimiento colocacion`,
                   y = `Cumplimiento Cartera`,
                   color = factor(Cluster))) +
  geom_point(alpha = 0.4, size = 1) +
  labs(color = "Cluster",
       x = "Cumplimiento Colocación",
       y = "Cumplimiento Cartera") +
  theme_minimal()

```

```{r}
table(Evalim$Cluster)
prop.table(table(Evalim$Cluster))
```
```{r}
colSums(is.na(Evalim))

```








```{r}
# centros en escala estandarizada (z-score)
centros_z <- km$centers                     # matriz 4x2

# parámetros de estandarización usados por scale()
mu  <- attr(features_scaled, "scaled:center")
sig <- attr(features_scaled, "scaled:scale")

# volver a escala original: x = z * sd + mean
centros_orig <- sweep(centros_z, 2, sig, `*`)
centros_orig <- sweep(centros_orig, 2, mu, `+`)
centros_orig


```
```{r}
library(dplyr)

Evalim %>%
  filter(!is.na(Cluster)) %>%
  group_by(Cluster) %>%
  summarise(
    n = n(),
    mean_cumpl_col = mean(`Cumplimiento colocacion`, na.rm = TRUE),
    median_cumpl_col = median(`Cumplimiento colocacion`, na.rm = TRUE),
    mean_cumpl_cart = mean(`Cumplimiento Cartera`, na.rm = TRUE),
    median_cumpl_cart = median(`Cumplimiento Cartera`, na.rm = TRUE)
  ) %>%
  arrange(desc(mean_cumpl_cart), desc(mean_cumpl_col))

```




















