---
title: "Prueba Tecnica"
output: html_notebook
---

# Limpieza de datos
```{r, echo=TRUE, message=FALSE, warning=FALSE}
#Bibliotecas
library(readxl)
library(dplyr)
library(ISOweek)
library(reshape2)
library(ggplot2)
library(writexl)


#Funciones
source("R/utils.R")

```





```{r}

Eva <- read_excel("Evaluación Consultor inteligencia de datos.xlsx")
Eva
```




```{r}
colSums(is.na(Eva))

```



```{r}

Evalim <- Eva %>%
  filter(if_all(everything(), ~ .x != "NA"))

Evalim <- na.omit(Evalim)
Evalim <- Evalim[Evalim$`ID empleado` != 0, ]

summary(Evalim)
```

```{r}
colSums(is.na(Evalim))

```


```{r}
conteo_unicos(Evalim)

```
```{r}

Evalim <- Evalim %>%
  mutate(
    `Semana ID` = ISOweek2date(
      paste0(substr(`Semana ID`, 1, 4), "-W", substr(`Semana ID`, 5, 6), "-1")
    )
  ) %>%
  arrange(`Semana ID`)    
Evalim
```

```{r}
colnames(Evalim)
```

# Analisis de datos

```{r}
# columnas que quieres graficar
cols <- c("Semanas de Antigüedad",
          "Colocación objetivo Asesor",
          "Colocación Total",
          "Cartera Vigente")

# vector de colores (se recicla si hay más columnas)
colores <- c("blue", "red", "green", "orange")

# for para graficar cada columna
for (i in seq_along(cols)) {
  colname <- cols[i]
  boxplot(Evalim[[colname]],
          main = colname,
          col  = colores[i])
}
```
```{r}

# for para graficar cada columna
for (i in seq_along(cols)) {
  colname <- cols[i]
  hist(Evalim[[colname]],
       main = colname,
       col  = colores[i],
       xlab = "")
}

```


```{r}

# sub-data frame con esas columnas
df_num <- Evalim[cols]

# calcular matriz de correlaciones
cor_mat <- cor(df_num, use = "complete.obs")



cor_long <- melt(cor_mat)

ggplot(cor_long, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(value, 2)), color = "black") +
  scale_fill_gradient2(low = "red", high = "blue", mid = "white",
                       midpoint = 0, limit = c(-1,1)) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(title = "Mapa de calor de correlaciones", x = "", y = "")

```





```{r}
library(ggplot2)

# 1. Antigüedad vs Colocación Total
ggplot(Evalim, aes(x = `Semanas de Antigüedad`, y = `Colocación Total`)) +
  geom_point(color = "steelblue1", alpha = 0.7, size = 2) +   # puntos azules
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "solid") + # línea roja
  labs(title = "Antigüedad vs Colocación Total",
       x = "Semanas de antigüedad",
       y = "Colocación Total") +
  theme_minimal()
```



```{r}
# 2. Antigüedad vs Cartera Vigente
ggplot(Evalim, aes(x = `Semanas de Antigüedad`, y = `Cartera Vigente`)) +
  geom_point(color = "lightgreen", alpha = 0.7, size = 2) +   # puntos verdes
  geom_smooth(method = "lm", se = FALSE, color = "orange", linetype = "solid") + # línea naranja
  labs(title = "Antigüedad vs Cartera Vigente",
       x = "Semanas de antigüedad",
       y = "Cartera Vigente") +
  theme_minimal()
```

```{r}
library(ggplot2)

# 1. Antigüedad vs Colocación objetivo Asesor
ggplot(Evalim, aes(x = `Semanas de Antigüedad`, y = `Colocación objetivo Asesor`)) +
  geom_point(color = "#EEEE00", alpha = 0.7, size = 2) +   # puntos azules
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "solid") + # línea roja
  labs(title = "Antigüedad vs Colocación objetivo Asesor",
       x = "Semanas de antigüedad",
       y = "Colocación objetivo Asesor") +
  theme_minimal()
```


# Modelos




```{r}
# Modelo 1: Y = Cartera Vigente, X = Semanas de Antigüedad + Colocación Total + Colocación objetivo Asesor
modelo1 <- lm(`Cartera Vigente` ~ `Semanas de Antigüedad` + `Colocación Total` + `Colocación objetivo Asesor`, 
              data = Evalim)

# Mostrar el resumen clásico
summary(modelo1)

```



```{r}
# Modelo 2: Y = Cartera Vigente, X = Semanas de Antigüedad
modelo2 <- lm(`Cartera Vigente` ~ `Semanas de Antigüedad`, data = Evalim)

# Resumen del modelo
summary(modelo2)


```
```{r}

# Predicción

Evalim$'Objetivo Cartera' <- predict(modelo1, newdata = Evalim)
Evalim
```

```{r}
# Cumplimiento
Evalim$'Cumplimiento Cartera' <- Evalim$`Cartera Vigente` / Evalim$'Objetivo Cartera'
Evalim
```


```{r}
Evalim$'Cumplimiento colocacion' <- Evalim$`Colocación Total` / Evalim$`Colocación objetivo Asesor`
Evalim
```

```{r}
colnames(Evalim)
```


```{r}
library(dplyr)

Evalim <- Evalim %>%
  mutate(
    Nivel_Prod = case_when(
      `Cumplimiento colocacion` > 1 & `Cumplimiento Cartera` > 1 ~ "4",
      `Cumplimiento colocacion` <= 1 & `Cumplimiento Cartera` > 1 ~ "3",
      `Cumplimiento colocacion` > 1 & `Cumplimiento Cartera` <= 1 ~ "2",
      TRUE ~ "1"
    )
  )

```


```{r}
table(Evalim$Nivel_Prod)
prop.table(table(Evalim$Nivel_Prod))

```
```{r}
colSums(is.na(Evalim))

```



















```{r}
library(ggplot2)

ggplot(Evalim, aes(x = `Cumplimiento colocacion`,
                   y = `Cumplimiento Cartera`,
                   color = Nivel_Prod)) +
  geom_point(alpha = 0.4, size = 1) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(color = "Nivel productividad",
       x = "Cumplimiento Colocación",
       y = "Cumplimiento Cartera") +
  theme_minimal()

```

```{r}
write_xlsx(Evalim, "Evalim.xlsx")

```


```{r}
set.seed(123)

# Matriz de features
features <- Evalim %>%
  select(`Cumplimiento colocacion`, `Cumplimiento Cartera`) %>%
  na.omit()

# Escalamos
features_scaled <- scale(features)

# k-means (4 clusters)
km <- kmeans(features_scaled, centers = 4, nstart = 25)

# Añadimos clusters al df
Evalim$Cluster <- NA
Evalim$Cluster[as.numeric(rownames(features))] <- km$cluster

```






```{r}
features <- Evalim %>%
  select(`Cumplimiento colocacion`, `Cumplimiento Cartera`) %>%
  filter(is.finite(`Cumplimiento colocacion`),
         is.finite(`Cumplimiento Cartera`))

# Escalar
features_scaled <- scale(features)

# k-means
set.seed(123)
km <- kmeans(features_scaled, centers = 4, nstart = 25)

```






```{r}
Evalim$Cluster <- NA
Evalim$Cluster[as.numeric(rownames(features))] <- km$cluster

```


```{r}
summary(features)
colSums(!is.finite(features))

```
















